### PR TITLE
Graph partition implementation from wolfram alpha script

### PR DESCRIPTION
**Pull request by TraistaRafael**

### CODE REVIEW

**Comment by paulsj-80** [comment]
- no need for print methods; cout << matrix is working
- random number: maybe it would be cool if that is possible to set it,
  and it is returned if from time()
- dot_product(): is it needed?
- magic number
  random_columns_index.resize(100, true);
- perform_graph_partition() function is too large, maybe it is worth to
  split it?
- tests are needed
  - inside /test folder
  - with Boost infrastructure (cases, asserts)
  - simple use cases
  - corner cases
  - triggering errors
    - invalid input data
- variable names: it is ok to use kk, ff, etc., but then surrounding
  context should be short and simple
  - solution: split into more functions
  - solution: give more meaningful names to variables
- more comments
- line 95:
  int k1 = kk1;
  - this value of k1 is never used
- line 97:
  int ko;
  - not used anywhere apart from setting it
- line 108, 109:
  - rename tt to something more meaningful
  - is there a guarantee it will always be set to 1?    
    - maybe can introduce maximum limit of repetitions, returning false
      if it is exceeded
      - in this case, function should return not bool, but rather an exit
        code
- code style: better everywhere
  if (something)
  not
  if(something)
  - reason is that functions are written without separating space; if,
    while are not functions
- please, add reference to paper which you were using when implementing
  particular algorithm

**Comment by TraistaRafael** [comment]
Thankyou for the detailed feedback! I will return with updates asap.

**Comment by TraistaRafael** [comment]
I commited with partial updates and tests. 
I consulted the feedback step by step, here is what is left to do:
1) perform_graph_partition() function is too large, maybe it is worth to
split it?
2) variables names
3) write more tests for corner cases, only 7 tests are available at this time
4) line 108, 109
Reference to the original paper: https://arxiv.org/pdf/1811.10470.pdf
Also the original wolfram matematica script:
[regu.zip](https://github.com/panda-official/metric/files/4238283/regu.zip)

**Comment by paulsj-80** [comment]
- keep_going should be int, which is reduced with each iteration always;
  it could be set to reasonably large number initially, and error would
  happen if it reaches 0
  int keep_going = MAX_CYCLE_ATTEMPTS;
  while (keep_going > 0) {
    ...
    if (some_good_condition) {
      keep_going = 0;
    }
    ...
    if (--keep_going == 0) {
      // throw exception?
      // return error code?
    }
  }
- perform_graph_partition()
  - can be split in functions, just need to invent names
    - for example:
                    for (int i = 0; i < rw.rows(); i++) {
                        double min = 0;
                        for (int j = 0; j < rw.columns(); j++) {
                            if (j == 0) {
                                ff[i] = 0;
                                min = rw(i, j);
                            }
                            else {
                                if (rw(i, j) < min) {
                                    min = rw(i, j);
                                    ff[i] = j;
                                }
                            }
                        }
                    }
    can be called as a function
      min = do_the_stuff(rw, ff);
    giving it appropriate name; this would make code much more readable
    - hint: try to keep various optimizations inside functions, so
      highest scope (inside perform_graph_partition()) doesn't see them,
      if that is possible
    - there has to be higher-level steps, done by the algorithm;
      ideally, function decomposition reflects those steps; each
      cycle is one of the first places where to look, if in doubt
    - if needed, use lambda expressions, but private functions are
      usual way to do it (they can be static, if object state is not
      changed)
  - variable names should be more descriptive, especially for those,
    which are used all throughout the function context (ff, rw); it
    is ok if they are long
  - partitioning_tests.cpp: probably it would be better to keep large
    matrix out of the code, store it in .csv file instead
    - reason: code readability

**Pull request closed without merging**
